[package]
name = "main"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_fundsp_13.workspace = true

[features]
dev = ["bevy/dynamic_linking",]