[package]
name = "foo"
version = "0.1.0"
edition = "2021"

authors.workspace = true

[dependencies]
bargo.workspace = true
bevy.workspace = true
bevy_rapier2d.workspace = true

[features]
dev = ["bevy/dynamic_linking",]